services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  cache.deepltranslate_glossary:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['deepltranslate_glossary']

  WebVision\Deepltranslate\Glossary\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  WebVision\Deepltranslate\Glossary\Service\DeeplGlossaryService:
    public: true
    arguments:
      $cache: '@cache.deepltranslate_glossary'

  WebVision\Deepltranslate\Glossary\EventListener\GlossarySyncButtonProvider:
    tags:
      - name: 'event.listener'
        identifier: 'glossary.syncbutton'
        event: TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent

  WebVision\Deepltranslate\Glossary\Upgrade\MigrateTablesFromOldStructureWizard:
    arguments:
      $cache: '@cache.runtime'

  WebVision\Deepltranslate\Glossary\Hooks\UpdatedGlossaryEntryTermHook:
    public: true

  WebVision\Deepltranslate\Glossary\EventListener\LocalGlossary:
    tags:
      - name: 'event.listener'
        class: WebVision\Deepltranslate\Core\Event\DeepLGlossaryIdEvent
        identifier: 'deepltranslate.localGlossary'

  WebVision\Deepltranslate\Glossary\EventListener\GlossaryModuleShouldNotRenderDeepLTranslationDropdown:
    tags:
      - name: 'event.listener'
        class: WebVision\Deepltranslate\Core\Event\RenderLocalizationSelectAllowed
        identifier: 'deepltranslate-glossary/forbidDropdownRendering'

  WebVision\Deepltranslate\Glossary\EventListener\ExcludeGlossaryTablesFromDeeplTranslation:
    tags:
      - name: 'event.listener'
        event: WebVision\Deepltranslate\Core\Event\DisallowTableFromDeeplTranslateEvent
        identifier: 'deepltranslate-glossary/disallow-entries'
